# Generated by Django 5.0 on 2023-12-13 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_category_featured_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='featured',
        ),
    ]
